<a href="https://colab.research.google.com/github/yamilethpuente/unidad1/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numPy es una libreria de python
numPy se utiliza para trabajar con matrices o arreglos
numPy es la abreviatura de "python numerico"
tambien tiene funciones para trabajar en el dominio de algebra lineal, la transformada y las matrices
en Python tenemos listas que sirven como matrices pero son lentas de procesar.
numPy tiene como objetivo proporcionar un objeto de matriz que sea 50 veces mas rapido que las listas tradicionales.

In [6]:
#primero tenemos que importar la libreria
import numpy

arreglo=numpy.array([1,2,3,4,5])
print ( arreglo)

[1 2 3 4 5]


numPy como np
numPy generalmente se importa bajo el alias np. python los alias son un nombre alternativo para referirse a la misma cosa

In [7]:
import numpy as np
arreglo=np.array([6,7,8,9,10])
print (arreglo)

[ 6  7  8  9 10]


comprobando la version de numPy la cadena de la version se almacena en el atributo __version__

In [5]:
import numpy as np
print (np.__version__)

2.0.2


numPy creando matrices
crear un objeto se utiliza para trabajar con matrices.
el objeto de matriz se llama ndarray.
podemos crear un numPy ndarray utilizando la funcion array()

In [10]:
import numpy as np
arreglo=np.array(["yamileth","ana","kimberly","yazmin"])
print (arreglo)
print (type(arreglo))

['yamileth' 'ana' 'kimberly' 'yazmin']
<class 'numpy.ndarray'>


dimenciones de matrices
una dimencion en matrices es un nivel
de profundidad de matriz (matrices anidadas)
una matriz anidada contiene matrices como elementos
matrices 0-D. son elementos de una matriz. cada valor de una matriz es una matriz 0-D.ejemplo: crea una matriz 0-Dcon un valor de 42

In [12]:
import numpy as np

arreglo=np.array(42)
print (arreglo)

42


matrices 1-D
una matriz que tiene matrices 0-D como elementos se denomina matriz unidimencional o 1-D estas son las matrices mas comunes y basicas.
ejemplo: crea una matriz de 1-D que tenga los valores 1,2,3,4,5

In [13]:
import numpy as np
arreglo=np.array ([1,2,3,4,5])
print (arreglo)

[1 2 3 4 5]


matrices 2D
una matriz que tiene matrices 1-D como elementos se denomina matris 2-D
a menudo se utilizan para representar matrices de segundo orden. NumPy tiene un submodulo completo dedicado a operaciones com matrices llamado numPy.mat.
ejemplo:crea una matriz de 2D que contenga dos matrices con los valores 123 y 456.

In [15]:
import numpy as np
arreglo=np.array([[1,2,3],[4,5,6]])
print(arreglo)

[[1 2 3]
 [4 5 6]]


matrices 3D
una matriz que tiene matrices 2D se denomina matriz 3D.
estas matrices se utilizan para representar una matriz de tercer orden.
ejemplo: crea una matriz 3D con dos matrices bidimencionales, ambas conteniendo dos matrices con los valores 1,2,3 y 4,5,6

In [17]:
import numpy as np
arreglo=np.array ([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print (arreglo)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
