<a href="https://colab.research.google.com/github/yamilethpuente/unidad1/blob/main/practica6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

yamileth puente uribe- 24 de septiembre de 2025 practica6- corta arreglos Numpy
-----------------------------------------------------
Slice en Python significa tomar elementos de un indice determinado a otro determinado indice
pasamos el Slice en lugar del indice de esta manera:[start:end ]
sino pasamos el inicio se concidera 0
sino pasamos el final, su longuitud es conciderado

In [3]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print (arreglo[1:5])

[2 3 4 5]


ejemplo 2
(1,2,3,4,5,6,7)
cortardel indice 4 hasta el final de la matriz
-------------------------

In [4]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print (arreglo[4:])

[5 6 7]


ejemplo 3 ([1,2,3,4,5,6,7])
cortarelementos desde el principio hasta el indice 5

In [5]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print (arreglo[:5])

[1 2 3 4 5]


ejemplo 4 ([1,2,3,4,5,6,7])
corte negativo.utilizamos el operador "menos" para hacer referencia a un indicedesde el final
---------------------------------------
cortar del indice 3 hasta el final el indice 1 desde el final

In [6]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print (arreglo[-3:-1])

[5 6]
